_wandb:
    value:
        cli_version: 0.19.1
        m:
            - "1": current_q
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": custom_epoch
              "6":
                - 3
              "7": []
            - "1": target_q
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": mean_P
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": mean_reward
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": mean_F1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": mean_similary
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Val/F1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Train/Loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": mean_R
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 75
                - 95
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 75
                - 95
            "3":
                - 7
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.1
            "6": 4.47.1
            "8":
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
batch_size:
    value: 8
epsilon:
    value: 0.5
gamma:
    value: 0.95
learning_rate:
    value: 0.0001
replay_buffer_size:
    value: 100
target_update:
    value: 10
